version: '1.0'
services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=pokemon
      - MYSQL_USER=node
      - MYSQL_PASSWORD=nodeapp
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3312:3312'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local